import type { Metadata } from 'next';
import './globals.css'; // optional if you want global styles

export const metadata: Metadata = {
  title: 'Chimpson Pickleball',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
